<a href="https://colab.research.google.com/github/keinam53/Deep_learning/blob/main/1_Wprowadzenie/2_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Tensor
1. [Import bibliotek](#a0)
2. [Skalar](#a1)
3. [Wektor](#a2)
4. [Tablica ~ macierz](#a3)
5. [Tensor](#a4)


### <a name='a0'></a> 1. Import bibliotek

In [1]:
import numpy as np

### <a name='a1'> </a> 2. Skalar 

In [2]:
skalar = 3
print(skalar)
print(type(skalar))

3
<class 'int'>


### <a name='a2'> </a> 3. Wektor

In [5]:
wektor = np.array([2, 4, -6, 5])
print(wektor)
print(wektor.dtype)
print(f'Rozmiar wektora: {wektor.shape}')
print(f'Rząd wektora: {wektor.ndim}')
print(f'Długość: {len(wektor)}')

[ 2  4 -6  5]
int64
Rozmiar wektora: (4,)
Rząd wektora: 1
Długość: 4


### <a name='a3'> </a> 4.Tablica ~ Macierz

In [7]:
macierz = np.array([[2, 6, 3],
                   [4, 6, 2]])
print(macierz)
print(macierz.dtype)
print(f'Rozmiar macierzy: {macierz.shape}')
print(f'Rząd macierzy: {macierz.ndim}')
print(f'Długość: {len(macierz)}')

[[2 6 3]
 [4 6 2]]
int64
Rozmiar macierzy: (2, 3)
Rząd macierzy: 2
Długość: 2


### <a name='a4'> </a> 5. Tensor

In [9]:
tensor = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [3, 5, 7]]])
print(tensor)
print(tensor.dtype)
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Rząd macierzy: {tensor.ndim}')
print(f'Długość: {len(tensor)}')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 5 7]]]
int64
Rozmiar macierzy: (2, 2, 3)
Rząd macierzy: 3
Długość: 2


In [10]:
tensor = np.array([
    [[1, 2, 3, 4],
     [4, 5, 6, 4],
     [4, 2, 5, 2]],
    [[7, 8, 9, 8],
     [3, 7, 3, 9],
     [5, 2, 4, 3]],
    [[2, 3, 5, 4],
     [7, 2, 5, 1],
     [8, 2, 7, 2]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]]
])
print(tensor)
print(tensor.dtype)
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Rząd macierzy: {tensor.ndim}')
print(f'Długość: {len(tensor)}')

[[[1 2 3 4]
  [4 5 6 4]
  [4 2 5 2]]

 [[7 8 9 8]
  [3 7 3 9]
  [5 2 4 3]]

 [[2 3 5 4]
  [7 2 5 1]
  [8 2 7 2]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]]
int64
Rozmiar macierzy: (5, 3, 4)
Rząd macierzy: 3
Długość: 5


In [11]:
tensor[0]

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [4, 2, 5, 2]])

In [12]:
tensor[1:3]

array([[[7, 8, 9, 8],
        [3, 7, 3, 9],
        [5, 2, 4, 3]],

       [[2, 3, 5, 4],
        [7, 2, 5, 1],
        [8, 2, 7, 2]]])